# CSV Configuration for Treasury Curve GAN Training

# Model configuration
model:
  gan_type: "wgan"  # Using WGAN for better stability
  generator:
    latent_dim: 128
    hidden_dims: [512, 1024, 512, 256]
    dropout: 0.2
  discriminator:
    hidden_dims: [256, 512, 256, 128]
    dropout: 0.2

# Data processing configuration
data_processing:
  sequence_length: 100
  batch_size: 64
  train_split: 0.7
  validation_split: 0.15
  test_split: 0.15
  min_sequence_length: 50
  max_sequence_length: 200

# Training configuration
training:
  epochs: 2000
  learning_rate_generator: 0.0001
  learning_rate_discriminator: 0.0001
  beta1: 0.5
  beta2: 0.9
  patience: 100
  critic_iterations: 5
  lambda_gp: 10.0
  batch_size: 64

# Data source configuration
data_source:
  csv_directory: "data/csv"
  file_patterns: ["*.csv"]
  encoding: "utf-8"
  delimiter: ","
  date_column: "date"
  numeric_columns_only: true
  remove_duplicates: true
  fill_missing: "forward"  # "forward", "backward", "interpolate", "drop"

# Feature engineering
features:
  include_spreads: true
  include_volatility: true
  volatility_window: 20
  normalization: "standard"  # "standard", "minmax", "robust" 