# GAN Configuration for Treasury Curve Data

# Data Configuration
data:
  batch_size: 32
  sequence_length: 100
  num_features: 125  # Updated to match actual data
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  
# Model Architecture
model:
  generator:
    latent_dim: 100
    hidden_dims: [256, 512, 1024, 512, 256]
    dropout: 0.3
    activation: "leaky_relu"
    
  discriminator:
    hidden_dims: [256, 512, 1024, 512, 256]
    dropout: 0.3
    activation: "leaky_relu"
    
# Training Configuration
training:
  epochs: 50  # Reduced for demonstration
  learning_rate_generator: 0.0002
  learning_rate_discriminator: 0.0002
  beta1: 0.5
  beta2: 0.999
  
  # GAN specific parameters
  critic_iterations: 5  # For WGAN
  lambda_gp: 10  # Gradient penalty weight
  
  # Early stopping
  patience: 20  # Reduced for demonstration
  min_delta: 0.001
  
# Loss weights
loss_weights:
  generator_loss: 1.0
  discriminator_loss: 1.0
  feature_matching: 0.1
  
# Data augmentation
augmentation:
  noise_factor: 0.01
  time_shift: 0.05
  
# Treasury instruments
instruments:
  - "2Y"
  - "5Y" 
  - "10Y"
  - "30Y"
  - "SOFR"
  
# Order book levels
order_book_levels: 5 