# GAN Configuration for Treasury Curve Training

# Model configuration
model:
  gan_type: "standard"  # "standard" or "wgan"
  generator:
    latent_dim: 100
    hidden_dims: [256, 512, 256, 128]
    dropout: 0.3
  discriminator:
    hidden_dims: [128, 256, 128, 64]
    dropout: 0.3

# Data configuration
data:
  sequence_length: 100
  num_features: 7  # 4 yields + 3 spreads
  batch_size: 32
  train_split: 0.7
  validation_split: 0.15
  test_split: 0.15

# Training configuration
training:
  epochs: 1000
  learning_rate_generator: 0.0002
  learning_rate_discriminator: 0.0002
  beta1: 0.5
  beta2: 0.999
  patience: 50
  critic_iterations: 5  # For WGAN
  lambda_gp: 10.0  # Gradient penalty weight for WGAN

# Instruments to include
instruments: ["2Y", "5Y", "10Y", "30Y"]

# Data source configuration
data_source:
  start_date: "2022-01-01"
  end_date: "2024-01-01"
  csv_directory: "data/csv" 