dashboard:
  auto_detected: true
  auto_detection: true
  port: 8082
  url: http://localhost:8082
data_processing:
  batch_size: 16
  num_features: 21
  sequence_length: 50
  test_split: 0.15
  train_split: 0.7
  validation_split: 0.15
data_source:
  csv_directory: data/csv
  csv_file: treasury_orderbook_sample.csv
instruments:
- 2Y
- 5Y
- 10Y
- 30Y
model:
  discriminator:
    dropout: 0.3
    hidden_dims:
    - 64
    - 128
    - 64
    - 32
  gan_type: standard
  generator:
    dropout: 0.3
    hidden_dims:
    - 128
    - 256
    - 128
    - 64
    latent_dim: 64
training:
  batch_size: 16
  beta1: 0.5
  beta2: 0.999
  critic_iterations: 5
  epochs: 5
  lambda_gp: 10.0
  learning_rate_discriminator: 0.0002
  learning_rate_generator: 0.0002
  patience: 50
